{{- if .Values.swimlanenode.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "swimlanepracticalchart.fullname" . }}-swimlanenode
  labels:
    app: {{ template "swimlanepracticalchart.name" . }}-swimlanenode
    chart: {{ template "swimlanepracticalchart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "swimlanepracticalchart.name" . }}-swimlanenode
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
{{- end -}}